# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python push to main - Run test and lint

on:
  push:
    branches: [ "main" ]
    paths: tempit/**.py
  pull_request:
    branches: [ "main" ]
    paths: tempit/**.py

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.x

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            pip install joblib

        - name: flake8 Lint
          uses: py-actions/flake8@v2
          with:
            ignore: "F401,E402,E302,E305,E265,E701"
            exclude: "examples/examples.py"
            max-line-length: "350"


        - name: Run unittests
          run: python -m unittest discover -v -s ./tests -p "*test*.py"